axi_my_calendar:
    # Configure allowed rendering for each recipe
    recipe_rendering:
        # Allows only the specified renderers
        only:
#            Axi\MyCalendar\Recipe\Now:
#                - Axi\MyCalendar\Renderer\NoneRenderer

        # Allows all available renderers but the ones listed here
        exclude:
            Axi\MyCalendar\Recipe\Now:
                - Axi\MyCalendar\Renderer\JsonRenderer
                - Axi\MyCalendar\Renderer\IcalRenderer
