name: Test & Lint

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  tools: php-cs-fixer, phpunit, composer
                  extensions: intl

            - name: Composer
              run: composer install

            - name: Test PhpCsFixer rules
              run: php-cs-fixer check

            - name: Run phpunit tests
              run: phpunit --bootstrap=vendor/autoload.php tests/
